export const ORDER_REPOSITORY = Symbol('ORDER_REPOSITORY');
export const ORDER_QUERIES = Symbol('ORDER_QUERIES');
export const ORDER_EVENT_PUBLISHER = Symbol('ORDER_EVENT_PUBLISHER');
export const QUEUE_METRICS = Symbol('QUEUE_METRICS');

export const CREATE_ORDER_USE_CASE = Symbol('CREATE_ORDER_USE_CASE');
export const GET_ORDER_USE_CASE = Symbol('GET_ORDER_USE_CASE');
export const LIST_ORDERS_USE_CASE = Symbol('LIST_ORDERS_USE_CASE');
export const GET_METRICS_SUMMARY_USE_CASE = Symbol('GET_METRICS_SUMMARY_USE_CASE');
export const GET_QUEUE_DEPTHS_USE_CASE = Symbol('GET_QUEUE_DEPTHS_USE_CASE');
