export const ORDER_REPOSITORY = Symbol('ORDER_REPOSITORY');
export const ORDER_QUERIES = Symbol('ORDER_QUERIES');
export const ORDER_EVENT_PUBLISHER = Symbol('ORDER_EVENT_PUBLISHER');
export const QUEUE_METRICS = Symbol('QUEUE_METRICS');
export const DEAD_LETTER_QUERIES = Symbol('DEAD_LETTER_QUERIES');
export const DEAD_LETTER_REPOSITORY = Symbol('DEAD_LETTER_REPOSITORY');
export const DEAD_LETTER_REPLAYER = Symbol('DEAD_LETTER_REPLAYER');
export const BREAKER_STATE_QUERIES = Symbol('BREAKER_STATE_QUERIES');

export const CREATE_ORDER_USE_CASE = Symbol('CREATE_ORDER_USE_CASE');
export const GET_ORDER_USE_CASE = Symbol('GET_ORDER_USE_CASE');
export const LIST_ORDERS_USE_CASE = Symbol('LIST_ORDERS_USE_CASE');
export const GET_METRICS_SUMMARY_USE_CASE = Symbol('GET_METRICS_SUMMARY_USE_CASE');
export const GET_QUEUE_DEPTHS_USE_CASE = Symbol('GET_QUEUE_DEPTHS_USE_CASE');
export const GET_THROUGHPUT_USE_CASE = Symbol('GET_THROUGHPUT_USE_CASE');
export const GET_BREAKER_STATE_USE_CASE = Symbol('GET_BREAKER_STATE_USE_CASE');
export const LIST_DEAD_LETTERS_USE_CASE = Symbol('LIST_DEAD_LETTERS_USE_CASE');
export const REPLAY_DEAD_LETTER_USE_CASE = Symbol('REPLAY_DEAD_LETTER_USE_CASE');
